# Generated by Django 3.0.5 on 2020-07-24 10:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=30)),
                ('Contact', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Created_at', models.DateTimeField(default=datetime.datetime(2020, 7, 24, 16, 38, 14, 783067))),
                ('Updated_at', models.DateTimeField(blank=True, default=None)),
                ('Content', models.TextField()),
                ('Author_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BLG.Author')),
            ],
        ),
    ]
