# Generated by Django 3.0.5 on 2020-07-18 11:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BLG', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 17, 12, 49, 877729)),
        ),
        migrations.AddField(
            model_name='blog',
            name='Updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 17, 12, 49, 877729)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Author_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BLG.Author'),
        ),
    ]
