# Generated by Django 3.0.5 on 2020-07-24 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLG', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 16, 45, 5, 339780)),
        ),
    ]
