# Generated by Django 3.0.5 on 2020-07-18 11:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BLG', '0002_auto_20200718_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 17, 17, 52, 15645)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Updated_at',
            field=models.DateTimeField(default=django.db.models.deletion.SET_NULL),
        ),
    ]
