# Generated by Django 3.0.5 on 2020-07-24 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLG', '0002_auto_20200724_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 16, 49, 7, 313054)),
        ),
    ]
