# Generated by Django 3.0.5 on 2020-07-18 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLG', '0003_auto_20200718_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 17, 19, 53, 496035)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Updated_at',
            field=models.DateTimeField(default=None),
        ),
    ]
