# Generated by Django 3.0.5 on 2020-07-24 11:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BLG', '0003_auto_20200724_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='author',
            name='Contact',
        ),
        migrations.AlterField(
            model_name='author',
            name='Name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 16, 58, 43, 455432)),
        ),
    ]
