# Generated by Django 3.0.5 on 2020-07-24 17:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BLG', '0004_auto_20200724_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Author_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 22, 52, 42, 515694)),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
