# Generated by Django 3.0.5 on 2020-07-18 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLG', '0005_auto_20200718_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 21, 52, 23, 859366)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Updated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
