# Generated by Django 3.0.5 on 2020-07-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLG', '0005_auto_20200724_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
