# Generated by Django 3.0.5 on 2020-07-18 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLG', '0006_auto_20200718_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 21, 53, 45, 130741)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Updated_at',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
