# Generated by Django 3.0.5 on 2020-07-24 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BLG', '0006_auto_20200724_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Author_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
